// <auto-generated />
namespace EntityFramework.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ManytomanyFluentAPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManytomanyFluentAPI));
        
        string IMigrationMetadata.Id
        {
            get { return "201708021753174_Many to many Fluent API"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
